# Generated by Django 5.1.3 on 2024-11-22 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Услуга')),
                ('description', models.TextField(max_length=250, verbose_name='Описание')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Цена')),
            ],
            options={
                'verbose_name': 'Услуга',
                'verbose_name_plural': 'Услуги',
                'ordering': ['name'],
                'permissions': [('can_add_service', 'Может добавлять услугу'), ('can_change_service', 'Может изменять услугу'), ('can_view_service', 'Может просматривать услугу')],
            },
        ),
    ]
