# Generated by Django 5.1.3 on 2024-11-28 03:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=255, verbose_name='Фамилия')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                ('patronymic', models.CharField(blank=True, max_length=255, null=True, verbose_name='Отчество')),
                ('specialization', models.TextField(max_length=511, verbose_name='Специализация')),
                ('qualification', models.CharField(max_length=255, verbose_name='Квалификация')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='doctors/')),
                ('experience', models.PositiveIntegerField(verbose_name='Стаж')),
            ],
            options={
                'verbose_name': 'врач',
                'verbose_name_plural': 'врачи',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Услуга')),
                ('description', models.TextField(blank=True, default='', null=True, verbose_name='Описание')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Цена')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.doctor', verbose_name='Оказывает услугу')),
            ],
            options={
                'verbose_name': 'Услуга',
                'verbose_name_plural': 'Услуги',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_date', models.DateField(verbose_name='Желаемая дата записи в формате 31.01.2020 ')),
                ('record_time', models.TimeField(verbose_name='Желаемое время записи в формате 10:00 ')),
                ('result', models.CharField(choices=[('Услуга пока не оказана.', 'Не оказано.'), ('Услуга оказана. Результаты диагностики высланы на Ваш e-mail', 'Оказано.')], default=('Услуга пока не оказана.', 'Не оказано.'))),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creator_record', to=settings.AUTH_USER_MODEL, verbose_name='Клиент')),
                ('doctor', models.ForeignKey(max_length=100, on_delete=django.db.models.deletion.CASCADE, to='main.service', verbose_name='Услуга')),
            ],
            options={
                'verbose_name': 'запись',
                'verbose_name_plural': 'записи',
            },
        ),
    ]
