# Generated by Django 5.1.3 on 2024-11-28 15:13

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='record_date',
            field=models.DateField(validators=[django.core.validators.MaxValueValidator(datetime.date(2024, 12, 26)), django.core.validators.MinValueValidator(datetime.date(2024, 11, 29))], verbose_name='Введите желаемую дату записи от 29.11.2024 до 26.12.2024'),
        ),
        migrations.AlterField(
            model_name='record',
            name='record_time',
            field=models.TimeField(validators=[django.core.validators.MinValueValidator(datetime.time(8, 0)), django.core.validators.MaxValueValidator(datetime.time(18, 0))], verbose_name='Желаемое время записи от 08:00 до 18:00'),
        ),
        migrations.AlterField(
            model_name='record',
            name='result',
            field=models.CharField(choices=[('Услуга пока не оказана.', 'Не оказано.'), ('Услуга оказана. Результаты диагностики высланы на Ваш e-mail', 'Оказано.')], default='Услуга пока не оказана.'),
        ),
    ]
