# Generated by Django 5.1.3 on 2024-11-23 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='description',
            field=models.TextField(default='', max_length=250, verbose_name='Описание'),
        ),
    ]
