# Generated by Django 5.1.3 on 2024-11-22 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_service_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                ('surname', models.CharField(max_length=255, verbose_name='Фамилия')),
                ('patronymic', models.CharField(blank=True, max_length=255, null=True, verbose_name='Отчество')),
                ('specialization', models.TextField(max_length=511, verbose_name='Специализация')),
                ('qualification', models.CharField(max_length=255, verbose_name='Квалификация')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='doctors/')),
                ('experience', models.PositiveIntegerField(verbose_name='Стаж')),
            ],
            options={
                'verbose_name': 'врач',
                'verbose_name_plural': 'врачи',
            },
        ),
    ]
