# Generated by Django 5.1.3 on 2024-11-29 12:54

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_record_record_date_alter_record_record_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='record_date',
            field=models.DateField(validators=[django.core.validators.MaxValueValidator(datetime.date(2024, 12, 27)), django.core.validators.MinValueValidator(datetime.date(2024, 11, 30))], verbose_name='Введите желаемую дату записи от 30.11.2024 до 27.12.2024'),
        ),
    ]
