# Generated by Django 5.1.3 on 2024-11-25 03:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_service_description'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата записи')),
                ('record_time', models.TimeField(verbose_name='Время записи')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Клиент')),
                ('doctor', models.ForeignKey(max_length=100, on_delete=django.db.models.deletion.CASCADE, to='main.doctor', verbose_name='Врач')),
            ],
            options={
                'verbose_name': 'запись',
                'verbose_name_plural': 'записи',
                'permissions': [('can_add_record', 'Может добавлять запись'), ('can_change_record', 'Может изменять запись'), ('can_view_record', 'Может просматривать запись'), ('can_delete_record', 'Может удалять запись')],
            },
        ),
    ]
