# Generated by Django 5.1.3 on 2024-11-25 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_service_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='record_date',
            field=models.DateField(verbose_name='Дата записи'),
        ),
    ]
