# Generated by Django 5.1.3 on 2024-11-25 06:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_record_record_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='doctor',
            field=models.ForeignKey(max_length=100, on_delete=django.db.models.deletion.CASCADE, to='main.service', verbose_name='Врач'),
        ),
    ]
