# Generated by Django 5.1.3 on 2024-11-25 06:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_record_doctor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='doctor',
            field=models.ForeignKey(max_length=100, on_delete=django.db.models.deletion.CASCADE, to='main.service', verbose_name='Услуга'),
        ),
        migrations.AlterField(
            model_name='record',
            name='record_date',
            field=models.DateField(verbose_name='Желаемая дата записи в формате 31.01.2020'),
        ),
        migrations.AlterField(
            model_name='record',
            name='record_time',
            field=models.TimeField(verbose_name='Желаемое время записи в формате 10:00'),
        ),
    ]
