# Generated by Django 5.1.3 on 2024-11-25 14:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_record_doctor_alter_record_record_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creator_record', to=settings.AUTH_USER_MODEL, verbose_name='Клиент'),
        ),
        migrations.AlterField(
            model_name='record',
            name='record_date',
            field=models.DateField(verbose_name='Желаемая дата записи в формате 31.01.2020 '),
        ),
        migrations.AlterField(
            model_name='record',
            name='record_time',
            field=models.TimeField(verbose_name='Желаемое время записи в формате 10:00 '),
        ),
    ]
