# Generated by Django 5.1.3 on 2024-11-26 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_record_client_alter_record_record_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='client',
            field=models.CharField(max_length=250, verbose_name='Клиент'),
        ),
    ]
